name: ehay
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  expandable_page_view: ^1.0.8
  flutter_countdown_timer: ^4.1.0
  flutter_easyloading: ^3.0.3
  get_storage: ^2.0.3
  http: ^0.13.4
  flutter_custom_clippers: ^2.0.0
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  flutter_credit_card: ^2.0.0
  ionicons: ^0.1.2
  flutter_phone_direct_caller: ^2.1.0
  infinite_scroll_pagination: ^3.1.0
  connectivity_plus: ^2.1.0

  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # stripe_payment: ^1.1.4
  # transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  change_app_package_name: ^1.0.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: GalaxyBT
      fonts:
        - asset: fonts/GalaxyBT.ttf
          style: italic
